#888    888 d8b 888                       d8b       .d8888b.  d8b                   d8b
#888    888 Y8P 888                       Y8P      d88P  Y88b Y8P                   Y8P
#888    888     888                                Y88b.
#8888888888 888 888  888  8888b.  888d888 888       "Y888b.   888  .d88b.  88888b.  888 88888b.   .d88b.
#888    888 888 888 .88P     "88b 888P"   888          "Y88b. 888 d88P"88b 888 "88b 888 888 "88b d88P"88b
#888    888 888 888888K  .d888888 888     888            "888 888 888  888 888  888 888 888  888 888  888
#888    888 888 888 "88b 888  888 888     888      Y88b  d88P 888 Y88b 888 888  888 888 888  888 Y88b 888
#888    888 888 888  888 "Y888888 888     888       "Y8888P"  888  "Y88888 888  888 888 888  888  "Y88888
#                                                                      888                            888
#                                                                 Y8b d88P                       Y8b d88P
#                                                                  "Y88P"                         "Y88P"
#ItemSigner Plugin Updated By HikariSpigot
#The Plugin runs on Java 17 or above

#The plugin has not only been updated but also optimized and support for HEX colors has been added!
#How to use HEX Colors: Add a '&' before every HEX (like below)
#Normal Color Codes also work ^^ Special color code like &l, &r, &o have to be at every word sadly (Maybe I will update this)




# Configure Messages
messages:
  prefix: '&#00fb9a&lHikariSigning &r&#00fb9a| &r&#00fb9a'
  no_permission: 'Du hast keine Rechte, um diesen Befehl zu nutzen.'
  no_item_in_hand: 'Du musst ein Item in deiner Hand halten, um es zu signieren!'
  unsign_not_allowed: 'Du kannst die Signatur nicht mehr entfernen!'
  successfully_signed: 'Du hast das Item erfolgreich signiert!'
  item_not_signed: 'Dieses Item ist nicht signiert!'
  successfully_unsigned: 'Du hast die Signatur von dem Item erfolgreich entfernt!'

  # Resign
  already_signed: 'Dieses Item ist bereits Signiert!'


allow:

  unsign: false

  resign: false


# %NAME% is the Name of the Player, %DATUM% the current Date, %UHRZEIT% the current Time.
format:
  - '&8○ &7Signiert von &b%NAME%'
  - '&8➥ &7Am &e%DATUM% &7um &e%UHRZEIT%'



# Permissions
permissions:

  sign: 'hikarisigning.sign'

  unsign: 'hikarisigning.unsign'

